export enum CourseDetailsTabs {
  TAB_OVERVIEW = 'TAB_OVERVIEW',
  TAB_LESSON = 'TAB_LESSON',
  TAB_EVALUATION_SYSTEM = 'TAB_EVALUATION_SYSTEM',
  TAB_REQUIREMENTS = 'TAB_REQUIREMENTS',
  TAB_TRAINING_METHODOLOGY = 'TAB_TRAINING_METHODOLOGY',
  TAB_OBJECTIVE = 'TAB_OBJECTIVE',
  TAB_ELIGIBILITY = 'TAB_ELIGIBILITY',
  TAB_TARGET_GROUP = 'TAB_TARGET_GROUP',
  TAB_TRAINER = 'TAB_TRAINER',
}

export enum CourseDetailsTabsForMuktopath {
  TAB_OBJECTIVE = 'TAB_OBJECTIVE',
  TAB_DETAILS = 'TAB_DETAILS',
  TAB_SYLLABUS = 'TAB_SYLLABUS',
  TAB_REQUIREMENTS = 'TAB_REQUIREMENTS',
  TAB_COURSE_REQUIREMENTS = 'TAB_COURSE_REQUIREMENTS',
}

export enum CoursePaymentTypes {
  COURSE_FEE_PAYMENT_AFTER_BATCH_ASSIGN = 1,
  COURSE_FEE_WITH_ADMISSION_FEE = 2,
}

export enum EnrollementSteps {
  GOTO_VERIFY_PAGE = 'GOTO_VERIFY_PAGE',
  GOTO_PAYMENT_PAGE = 'GOTO_PAYMENT_PAGE',
  GOTO_ENROLLMENT_MULTIPLE = 'GOTO_ENROLLMENT_MULTIPLE',
  GOTO_ENROLLMENT_FIRST_TIME = 'GOTO_ENROLLMENT_FIRST_TIME',
  GOTO_PREVIOUS_ENROLLMENT = 'GOTO_PREVIOUS_ENROLLMENT',
  NOT_ENROLLABLE = 'NOT_ENROLLABLE',
}

export enum PaymentStatus {
  UN_PAID = 0,
  SUCCESS = 1,
  PARTIAL = 2,
}
