export enum CERTIFICATE_TYPE {
  COMPETENT_NOT_COMPETENT = 1,
  GRADING = 2,
  MARKS = 3,
  PARTICIPATION = 4,
  MEMBER_REGISTRATION = 6,
}

export const CERTIFICATE_LANGUAGE = {
  BANGLA: 1,
  ENGLISH: 2,
};
