type Institute = {
  id: number;
  title_en: string;
  title: string;
  code: string;
  domain: string;
  address: string;
  google_map_src: string;
  logo: string;
  primary_phone: string;
  phone_numbers: Array<object>;
  primary_mobile: string;
  mobile_numbers: Array<object>;
  email: string;
  config: string;
  row_status: string;
  created_at?: string;
  updated_at?: string;
  deleted_at?: string;
};

type Programme = {
  id: number;
  title_en?: string;
  title: string;
  institute_id: string | number;
  institute_title_en?: string;
  code?: string;
  logo?: string;
  description?: string;
  description_en?: string;
  row_status: string;
  created_at?: string;
  updated_at?: string;
  deleted_at?: string;
};

type Course = {
  id: string;
  code: string;
  institute_id: number | string;
  institute_title?: string;
  institute_title_en?: string;
  branch_id?: number | string;
  branch_title?: string;
  branch_title_en?: string;
  program_id?: number | string;
  program_title?: string;
  program_title_en?: string;
  level: number | string;
  language_medium: number | string;
  skills: Array[number | string];
  title_en: string;
  title: string;
  course_fee: string;
  duration?: string;
  target_group?: string;
  target_group_en?: string;
  overview?: string;
  overview_en?: string;
  objectives?: string;
  objectives_en?: string;
  training_methodology?: string;
  training_methodology_en?: string;
  evaluation_system?: string;
  evaluation_system_en?: string;
  prerequisite?: string;
  prerequisite_en?: string;
  eligibility?: string;
  eligibility_en?: string;
  cover_image?: string;
  row_status: string;
  crated_by?: string;
  updated_by?: string;
  created_at?: string;
  updated_at?: string;
  deleted_at?: string;
  dynamic_form_field: string | object;
  application_form_settings: string | object;
};

type Trainer = {
  id: number;
  institute_id?: number | string;
  trainer_first_name_en?: string;
  trainer_first_name: string;
  branch_id?: number | string;
  training_center_id?: number | string;
  trainer_registration_number: number | string;
  email: string;
  mobile: string;
  date_of_birth: string;
  about_me?: string;
  about_me_en?: string;
  gender: number | string;
  marital_status: number | string;
  religion?: number | string;
  nationality: string;
  nid?: string;
  passport_number?: string;
  present_address_division_id?: number | string;
  present_address_district_id?: number | string;
  present_address_upazila_id?: number | string;
  permanent_address_district_id?: number | string;
  permanent_address_upazila_id?: number | string;
  permanent_address_division_id?: number | string;
  present_house_address?: string;
  present_house_address_en?: string;
  permanent_house_address?: string;
  permanent_house_address_en?: string;
  educational_qualification?: string;
  educational_qualification_en?: string;
  photo?: string;
  signature?: string;
  skills?: string;
  skills_en?: string;
  row_status?: string;
  updated_at?: string;
  crated_at?: string;
};

type Batch = {
  id: number;
  title_en?: string;
  title: string;
  institute_id: number | string;
  course_id: number | string;
  training_center_id: number | string;
  branch_id: number | string;
  number_of_seats: number | string;
  available_seats: number | string;
  registration_start_date: string;
  registration_end_date: string;
  batch_start_date: string;
  batch_end_date: string;
  row_status: string;
  trainers?: Array<number>;
  crated_by?: string;
  updated_by?: string;
  created_at?: string;
  updated_at?: string;
  deleted_at?: string;
};

type Application = {
  id: number;
  Gender: string;
  full_name: string;
  course_name: string;
  username: string;
  user_name_type: number;
  first_name: string;
  last_name: string;
  gender: number;
  email: string;
  mobile: string;
  date_of_birth: string;
  physical_disability_status: number;
  loc_division_id: number;
  loc_district_id: number;
  row_status: number;
  approval_status: string;
  accepted: number;
  rejected: number;
  created_at: string;
  updated_at: string;
};
